export type ModuleStatus = 'completed' | 'in-progress' | 'not-started'

export type CourseModule = {
    id: string
    title: string
    description: string
    lessons: number
    labs: number
    hours: string
    difficulty: 'Easy' | 'Medium' | 'Hard'
    completion: number       // 0–100
    status: ModuleStatus
}

export type Course = {
    id: string
    title: string
    description: string
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
    duration: string
    userCount: number
    category: string
    color: string
    icon: string
    modules: CourseModule[]
}

export const COURSES: Course[] = [
    {
        id: '1',
        title: 'Introduction to Cybersecurity',
        description: 'Learn the foundational concepts of cybersecurity, including threat landscapes, security principles, and how to protect digital assets in modern environments.',
        difficulty: 'Beginner',
        duration: '4h 30m',
        userCount: 214,
        category: 'Security Fundamentals',
        color: 'from-violet-600 to-purple-800',
        icon: '🛡️',
        modules: [
            {
                id: '1-1',
                title: 'What is Cybersecurity?',
                description: 'An introduction to the cybersecurity landscape, key definitions, and why security matters in the modern world.',
                lessons: 5,
                labs: 1,
                hours: '1h 00m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '1-2',
                title: 'Threat Actors & Motivations',
                description: 'Explore who carries out attacks, their motivations, and the categories of threats organizations face daily.',
                lessons: 4,
                labs: 1,
                hours: '45m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '1-3',
                title: 'Security Principles & Frameworks',
                description: 'Learn about the CIA triad, defence in depth, and widely adopted security frameworks like NIST and ISO 27001.',
                lessons: 6,
                labs: 2,
                hours: '1h 15m',
                difficulty: 'Easy',
                completion: 60,
                status: 'in-progress',
            },
            {
                id: '1-4',
                title: 'Protecting Digital Assets',
                description: 'Practical techniques for protecting data, devices, and accounts at an individual and organizational level.',
                lessons: 5,
                labs: 2,
                hours: '1h 00m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '1-5',
                title: 'Assessment & Certification',
                description: 'Test your understanding with a final assessment covering all topics from this course.',
                lessons: 1,
                labs: 0,
                hours: '30m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '2',
        title: 'Phishing Awareness & Defense',
        description: 'Understand how phishing attacks work, learn to identify social engineering tactics, and build habits to protect yourself and your organization from credential theft.',
        difficulty: 'Beginner',
        duration: '2h 15m',
        userCount: 389,
        category: 'Social Engineering',
        color: 'from-rose-600 to-red-800',
        icon: '🎣',
        modules: [
            {
                id: '2-1',
                title: 'Anatomy of a Phishing Attack',
                description: 'Break down a real phishing campaign end-to-end: lures, landing pages, credential harvesting, and persistence.',
                lessons: 4,
                labs: 1,
                hours: '40m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '2-2',
                title: 'Identifying Red Flags',
                description: 'Practical exercises to spot suspicious emails, spoofed domains, and social engineering attempts before they succeed.',
                lessons: 5,
                labs: 2,
                hours: '50m',
                difficulty: 'Easy',
                completion: 75,
                status: 'in-progress',
            },
            {
                id: '2-3',
                title: 'Reporting & Response',
                description: 'How to report suspected phishing internally and the steps to follow if you\'ve already clicked a malicious link.',
                lessons: 3,
                labs: 1,
                hours: '45m',
                difficulty: 'Easy',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '3',
        title: 'Network Security Essentials',
        description: 'Explore core network security concepts including firewalls, VPNs, intrusion detection systems, and best practices for securing organizational infrastructure.',
        difficulty: 'Intermediate',
        duration: '6h 00m',
        userCount: 132,
        category: 'Networking',
        color: 'from-blue-600 to-indigo-800',
        icon: '🔗',
        modules: [
            {
                id: '3-1',
                title: 'Network Fundamentals Recap',
                description: 'A refresher on OSI model, TCP/IP, subnetting, and packet flow — the foundation for everything that follows.',
                lessons: 5,
                labs: 2,
                hours: '1h 30m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '3-2',
                title: 'Firewalls & Access Control',
                description: 'Configure stateful firewalls, ACLs, and DMZ architectures to enforce least-privilege network access.',
                lessons: 6,
                labs: 3,
                hours: '1h 30m',
                difficulty: 'Medium',
                completion: 100,
                status: 'completed',
            },
            {
                id: '3-3',
                title: 'VPNs & Encrypted Tunnels',
                description: 'Deploy and troubleshoot IPsec and TLS-based VPNs for secure remote access and site-to-site connectivity.',
                lessons: 5,
                labs: 2,
                hours: '1h 15m',
                difficulty: 'Medium',
                completion: 45,
                status: 'in-progress',
            },
            {
                id: '3-4',
                title: 'Intrusion Detection & Prevention',
                description: 'Set up and tune IDS/IPS solutions, understand signature vs. behavioural detection, and handle alerts.',
                lessons: 4,
                labs: 2,
                hours: '1h 00m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '3-5',
                title: 'Network Monitoring & Hardening',
                description: 'Apply CIS benchmarks, monitor traffic with NetFlow, and use SIEM integration to detect anomalies.',
                lessons: 4,
                labs: 2,
                hours: '45m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '4',
        title: 'Secure Coding Practices',
        description: 'Learn how to write secure code by understanding common vulnerabilities like SQL injection, XSS, and CSRF, and how to defend against them using industry best practices.',
        difficulty: 'Intermediate',
        duration: '5h 45m',
        userCount: 98,
        category: 'Development',
        color: 'from-emerald-600 to-teal-800',
        icon: '💻',
        modules: [
            {
                id: '4-1',
                title: 'OWASP Top 10 Overview',
                description: 'Survey the ten most critical web application security risks with real-world examples and mitigation strategies.',
                lessons: 5,
                labs: 1,
                hours: '1h 00m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '4-2',
                title: 'Injection Attacks',
                description: 'Deep-dive into SQL, command, and LDAP injection — exploit them in a lab environment, then learn to prevent them.',
                lessons: 6,
                labs: 3,
                hours: '1h 30m',
                difficulty: 'Medium',
                completion: 30,
                status: 'in-progress',
            },
            {
                id: '4-3',
                title: 'XSS & CSRF',
                description: 'Understand reflected, stored, and DOM-based XSS alongside CSRF attacks, and implement robust defences.',
                lessons: 5,
                labs: 2,
                hours: '1h 15m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '4-4',
                title: 'Authentication & Session Management',
                description: 'Implement secure authentication flows, session tokens, and MFA to eliminate common account-takeover vectors.',
                lessons: 4,
                labs: 2,
                hours: '1h 00m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '4-5',
                title: 'Dependency & Supply Chain Security',
                description: 'Audit third-party libraries, use SBOMs, and integrate SCA tooling into your CI/CD pipeline.',
                lessons: 3,
                labs: 1,
                hours: '1h 00m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '5',
        title: 'Data Privacy & GDPR Compliance',
        description: 'Gain a comprehensive understanding of data privacy regulations, how GDPR affects your organization, and practical steps to ensure compliance and protect user data.',
        difficulty: 'Beginner',
        duration: '3h 00m',
        userCount: 451,
        category: 'Compliance',
        color: 'from-amber-500 to-orange-700',
        icon: '📋',
        modules: [
            {
                id: '5-1',
                title: 'Introduction to Data Privacy',
                description: 'Foundational principles of data privacy, the difference between privacy and security, and why it matters for organizations.',
                lessons: 4,
                labs: 0,
                hours: '45m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '5-2',
                title: 'GDPR Key Principles',
                description: 'Unpack the seven GDPR principles, lawful bases for processing, and what each means in practice for your team.',
                lessons: 5,
                labs: 0,
                hours: '1h 00m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '5-3',
                title: 'Data Subject Rights & Breach Notification',
                description: 'Implement processes for handling data access requests, right-to-erasure, and mandatory breach reporting obligations.',
                lessons: 4,
                labs: 1,
                hours: '1h 15m',
                difficulty: 'Medium',
                completion: 20,
                status: 'in-progress',
            },
        ],
    },
    {
        id: '6',
        title: 'Incident Response & Forensics',
        description: 'Develop skills to effectively respond to security incidents: from detection and containment to investigation, evidence collection, and post-incident recovery.',
        difficulty: 'Advanced',
        duration: '8h 30m',
        userCount: 67,
        category: 'Incident Response',
        color: 'from-sky-600 to-cyan-800',
        icon: '🔍',
        modules: [
            {
                id: '6-1',
                title: 'IR Lifecycle & Team Roles',
                description: 'Understand NIST\'s incident response lifecycle and how to structure an effective computer security incident response team (CSIRT).',
                lessons: 4,
                labs: 1,
                hours: '1h 00m',
                difficulty: 'Medium',
                completion: 100,
                status: 'completed',
            },
            {
                id: '6-2',
                title: 'Detection & Triage',
                description: 'Use SIEM alerts, endpoint telemetry, and threat intelligence feeds to detect, categorize, and prioritize incidents.',
                lessons: 5,
                labs: 2,
                hours: '1h 30m',
                difficulty: 'Hard',
                completion: 80,
                status: 'in-progress',
            },
            {
                id: '6-3',
                title: 'Containment & Eradication',
                description: 'Apply network isolation, account remediation, and malware removal techniques to stop an active incident.',
                lessons: 5,
                labs: 3,
                hours: '2h 00m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '6-4',
                title: 'Digital Forensics Fundamentals',
                description: 'Collect and preserve forensic evidence from memory, disk, and network captures while maintaining chain of custody.',
                lessons: 6,
                labs: 3,
                hours: '2h 30m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '6-5',
                title: 'Post-Incident Review',
                description: 'Conduct blameless post-mortems, produce incident reports, and apply lessons learned to prevent recurrence.',
                lessons: 3,
                labs: 1,
                hours: '1h 30m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '7',
        title: 'Cloud Security Fundamentals',
        description: 'Understand the shared responsibility model, the most common cloud misconfigurations, and how to secure workloads across AWS, Azure, and Google Cloud environments.',
        difficulty: 'Intermediate',
        duration: '5h 15m',
        userCount: 176,
        category: 'Cloud',
        color: 'from-fuchsia-600 to-pink-800',
        icon: '☁️',
        modules: [
            {
                id: '7-1',
                title: 'Shared Responsibility Model',
                description: 'Clarify the boundaries between cloud provider and customer security obligations across IaaS, PaaS, and SaaS.',
                lessons: 3,
                labs: 0,
                hours: '45m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '7-2',
                title: 'Identity & Access Management in the Cloud',
                description: 'Configure IAM policies, service accounts, and role-based access control correctly to prevent privilege escalation.',
                lessons: 5,
                labs: 2,
                hours: '1h 15m',
                difficulty: 'Medium',
                completion: 50,
                status: 'in-progress',
            },
            {
                id: '7-3',
                title: 'Storage & Data Security',
                description: 'Avoid common S3/blob misconfiguration pitfalls, apply encryption at rest and in transit, and audit access logs.',
                lessons: 4,
                labs: 2,
                hours: '1h 00m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '7-4',
                title: 'Container & Serverless Security',
                description: 'Harden Docker images, Kubernetes clusters, and serverless functions against common attack techniques.',
                lessons: 5,
                labs: 3,
                hours: '1h 30m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '7-5',
                title: 'Cloud Security Posture Management',
                description: 'Use CSPM tools to continuously detect drift, enforce guardrails, and maintain compliance across multi-cloud environments.',
                lessons: 3,
                labs: 1,
                hours: '45m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
    {
        id: '8',
        title: 'Penetration Testing Basics',
        description: 'Get hands-on with ethical hacking methodologies. Learn reconnaissance, vulnerability assessment, exploitation techniques, and responsible disclosure practices.',
        difficulty: 'Advanced',
        duration: '10h 00m',
        userCount: 54,
        category: 'Offensive Security',
        color: 'from-slate-600 to-gray-800',
        icon: '⚔️',
        modules: [
            {
                id: '8-1',
                title: 'Pentesting Methodology & Legal Scope',
                description: 'Understand the phases of a penetration test, rules of engagement, and how to stay within legal boundaries.',
                lessons: 3,
                labs: 0,
                hours: '45m',
                difficulty: 'Easy',
                completion: 100,
                status: 'completed',
            },
            {
                id: '8-2',
                title: 'Reconnaissance & OSINT',
                description: 'Use passive and active reconnaissance techniques to gather intelligence on targets before exploitation.',
                lessons: 5,
                labs: 2,
                hours: '1h 30m',
                difficulty: 'Medium',
                completion: 100,
                status: 'completed',
            },
            {
                id: '8-3',
                title: 'Vulnerability Scanning',
                description: 'Run Nessus, OpenVAS, and Nmap scans to enumerate services and identify exploitable vulnerabilities.',
                lessons: 4,
                labs: 2,
                hours: '1h 15m',
                difficulty: 'Medium',
                completion: 40,
                status: 'in-progress',
            },
            {
                id: '8-4',
                title: 'Exploitation Fundamentals',
                description: 'Execute controlled exploits using Metasploit, understand payloads, and establish limited post-exploitation footholds.',
                lessons: 6,
                labs: 4,
                hours: '2h 30m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '8-5',
                title: 'Reporting & Disclosure',
                description: 'Write clear, professional penetration test reports and understand responsible vulnerability disclosure procedures.',
                lessons: 3,
                labs: 1,
                hours: '1h 00m',
                difficulty: 'Medium',
                completion: 0,
                status: 'not-started',
            },
            {
                id: '8-6',
                title: 'Capstone: Full Pentest Simulation',
                description: 'Execute a full simulated penetration test against a vulnerable target environment from recon to report.',
                lessons: 1,
                labs: 5,
                hours: '3h 00m',
                difficulty: 'Hard',
                completion: 0,
                status: 'not-started',
            },
        ],
    },
]
