import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.getByRole('textbox', { name: 'Username or email' }).click();
    await page.getByRole('textbox', { name: 'Username or email' }).fill('platform_admin');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('admin');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('admin@admin.pt');
    await page.getByRole('textbox', { name: 'First name' }).click();
    await page.getByRole('textbox', { name: 'First name' }).fill('platform');
    await page.getByRole('textbox', { name: 'Last name' }).click();
    await page.getByRole('textbox', { name: 'Last name' }).fill('admin');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('link', { name: 'Tenants', exact: true }).click();
    await page.getByRole('button', { name: 'New Tenant' }).click();
    await page.getByRole('textbox', { name: 'Organization name*' }).click();
    await page.getByRole('textbox', { name: 'Organization name*' }).fill('ua');
    await page.getByRole('textbox', { name: 'Tenant domain/email pattern*' }).click();
    await page.getByRole('textbox', { name: 'Tenant domain/email pattern*' }).fill('ua.pt');
    await page.getByRole('textbox', { name: 'Admin email*' }).click();
    await page.getByRole('textbox', { name: 'Admin email*' }).fill('admin@ua.pt');
    await page.locator('.absolute').first().click();
    await page.locator('.lucide.lucide-check.w-3.h-3.text-white').click();
    await page.locator('.lucide.lucide-check').first().click();
    await page.getByText('Learning ManagementDeliver').click();
    await page.getByRole('button', { name: 'Upload tenant logo' }).click();
    await page.getByRole('button', { name: 'Create Tenant' }).click();
    await page.getByText('Realm created successfully!').click();
});