import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/admin');
  await page.getByRole('textbox', { name: 'Username or email' }).fill('platform_admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('platform_admina');
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('platform_admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('u@admin.pt');
  await page.getByRole('textbox', { name: 'First name' }).click();
  await page.getByRole('textbox', { name: 'First name' }).fill('platform');
  await page.getByRole('textbox', { name: 'Last name' }).click();
  await page.getByRole('textbox', { name: 'Last name' }).fill('admin');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Tenants', exact: true }).click();
  await page.getByRole('button', { name: 'New Tenant' }).click();
  await page.getByRole('textbox', { name: 'Organization name*' }).click();
  await page.getByRole('textbox', { name: 'Organization name*' }).fill('ua');
  await page.getByRole('textbox', { name: 'Tenant domain/email pattern*' }).click();
  await page.getByRole('textbox', { name: 'Tenant domain/email pattern*' }).fill('ua.pt');
  await page.getByRole('textbox', { name: 'Admin email*' }).click();
  await page.getByRole('textbox', { name: 'Admin email*' }).fill('admin@ua.pt');
  await page.getByRole('button', { name: 'Create Tenant' }).click();
  await page.waitForTimeout(3000);
  await page.goto('http://localhost:5173/');
  await page.getByRole('textbox', { name: 'name@company.com' }).click();
  await page.getByRole('textbox', { name: 'name@company.com' }).fill('user@ua.pt');
  await page.getByRole('button').click();
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('org_manager');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('org_manager1');
  await page.getByRole('textbox', { name: 'Password' }).fill('2');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('org_manager');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'User Management' }).click();
  await page.getByRole('button', { name: 'New User' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).fill('user');
  await page.getByRole('textbox', { name: 'john.doe@example.com' }).click();
  await page.getByRole('textbox', { name: 'john.doe@example.com' }).fill('user@ua.pt');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('user');
  await page.getByRole('button', { name: 'User', exact: true }).click();
  await page.getByRole('button', { name: 'Create User' }).click();
  await page.getByRole('link', { name: 'User groups' }).click();
  await page.getByRole('link', { name: 'Create New Group' }).click();
  await page.getByRole('textbox', { name: 'Group Name *' }).click();
  await page.getByRole('textbox', { name: 'Group Name *' }).fill('DEV_default');
  await page.getByRole('textbox', { name: 'Search by name, email, or' }).click();
  await page.getByRole('textbox', { name: 'Search by name, email, or' }).fill('user');
  await page.getByTestId('user-result-user@ua.pt').click();
  await page.getByRole('button', { name: 'Create Group' }).click();
  await page.goto('http://localhost:8080/');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByTestId('nav-item-realms').click();
  await page.getByRole('link', { name: 'ua' }).click();
  await page.getByTestId('nav-item-clients').click();
  await page.getByTestId('nav-item-users').click();
  await page.getByTestId('users-page').getByRole('link', { name: 'user' }).click();
  await page.getByTestId('credentials').click();
  await page.getByTestId('resetPasswordBtn').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Kebab toggle' }).click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByTestId('confirm').click();
  await page.getByTestId('no-credentials-empty-action').click();
  await page.getByTestId('no-credentials-empty-action').click();
  await page.getByTestId('passwordField').click();
  await page.getByTestId('passwordField').fill('1234');
  await page.getByRole('button', { name: 'Show password field in clear' }).first().click();
  await page.getByTestId('passwordConfirmationField').click();
  await page.getByTestId('passwordConfirmationField').fill('1234');
  await page.locator('.pf-v5-c-switch.pf-v5-u-mb-md > .pf-v5-c-switch__toggle').click();
  await page.getByTestId('confirm').click();
  await page.getByTestId('confirm').click();
  await page.waitForTimeout(3000);
  await page.goto('http://localhost:5173/dashboard');
});