sonar.projectKey=PEI-SecureLearning_smtp
sonar.organization=pei-securelearning
sonar.projectName=SecureLearning SMTP

sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclude generated / non-source
sonar.exclusions=**/__pycache__/**,**/*.pyc
