/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsOrgManagerRouteImport } from './routes/tenants-org-manager'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplianceOrgManagerRouteImport } from './routes/compliance-org-manager'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsergroupsIndexRouteImport } from './routes/usergroups/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as SendingProfilesIndexRouteImport } from './routes/sending-profiles/index'
import { Route as PhishingKitsIndexRouteImport } from './routes/phishing-kits/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ContentManagerIndexRouteImport } from './routes/content-manager/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsergroupsNewGroupRouteImport } from './routes/usergroups/new-group'
import { Route as UsergroupsIdRouteImport } from './routes/usergroups/$id'
import { Route as TenantsNewTenantRouteImport } from './routes/tenants/new-tenant'
import { Route as TenantsIdRouteImport } from './routes/tenants/$id'
import { Route as SendingProfilesNewRouteImport } from './routes/sending-profiles/new'
import { Route as SendingProfilesIdRouteImport } from './routes/sending-profiles/$id'
import { Route as PhishingKitsNewRouteImport } from './routes/phishing-kits/new'
import { Route as PhishingKitsIdRouteImport } from './routes/phishing-kits/$id'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as ContentManagerTemplatesRouteImport } from './routes/content-manager/templates'
import { Route as ContentManagerSettingsRouteImport } from './routes/content-manager/settings'
import { Route as ContentManagerReportRouteImport } from './routes/content-manager/report'
import { Route as ContentManagerModulesRouteImport } from './routes/content-manager/modules'
import { Route as ContentManagerHelpRouteImport } from './routes/content-manager/help'
import { Route as ContentManagerCoursesRouteImport } from './routes/content-manager/courses'
import { Route as ContentManagerContentRouteImport } from './routes/content-manager/content'
import { Route as CampaignsTimelineRouteImport } from './routes/campaigns/timeline'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportRouteImport } from './routes/admin/report'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses/$courseId/index'
import { Route as CampaignsIdIndexRouteImport } from './routes/campaigns/$id/index'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin/tenants/index'
import { Route as ContentManagerModulesNewRouteImport } from './routes/content-manager/modules_.new'
import { Route as ContentManagerModulesModuleIdRouteImport } from './routes/content-manager/modules_.$moduleId'
import { Route as ContentManagerCoursesNewRouteImport } from './routes/content-manager/courses_.new'
import { Route as ContentManagerCoursesCourseIdRouteImport } from './routes/content-manager/courses_.$courseId'
import { Route as ContentManagerContentContentPieceIdRouteImport } from './routes/content-manager/content.$contentPieceId'
import { Route as CampaignsIdEditRouteImport } from './routes/campaigns/$id/edit'
import { Route as AdminTenantsNewTenantRouteImport } from './routes/admin/tenants/new-tenant'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin/tenants/$tenantId'
import { Route as CoursesCourseIdModulesModuleIdRouteImport } from './routes/courses/$courseId/modules/$moduleId'
import { Route as ContentManagerCoursesCourseIdEditRouteImport } from './routes/content-manager/courses_.$courseId_.edit'

const TenantsOrgManagerRoute = TenantsOrgManagerRouteImport.update({
  id: '/tenants-org-manager',
  path: '/tenants-org-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceOrgManagerRoute = ComplianceOrgManagerRouteImport.update({
  id: '/compliance-org-manager',
  path: '/compliance-org-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsergroupsIndexRoute = UsergroupsIndexRouteImport.update({
  id: '/usergroups/',
  path: '/usergroups/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SendingProfilesIndexRoute = SendingProfilesIndexRouteImport.update({
  id: '/sending-profiles/',
  path: '/sending-profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingKitsIndexRoute = PhishingKitsIndexRouteImport.update({
  id: '/phishing-kits/',
  path: '/phishing-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerIndexRoute = ContentManagerIndexRouteImport.update({
  id: '/content-manager/',
  path: '/content-manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UsergroupsNewGroupRoute = UsergroupsNewGroupRouteImport.update({
  id: '/usergroups/new-group',
  path: '/usergroups/new-group',
  getParentRoute: () => rootRouteImport,
} as any)
const UsergroupsIdRoute = UsergroupsIdRouteImport.update({
  id: '/usergroups/$id',
  path: '/usergroups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewTenantRoute = TenantsNewTenantRouteImport.update({
  id: '/tenants/new-tenant',
  path: '/tenants/new-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SendingProfilesNewRoute = SendingProfilesNewRouteImport.update({
  id: '/sending-profiles/new',
  path: '/sending-profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SendingProfilesIdRoute = SendingProfilesIdRouteImport.update({
  id: '/sending-profiles/$id',
  path: '/sending-profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingKitsNewRoute = PhishingKitsNewRouteImport.update({
  id: '/phishing-kits/new',
  path: '/phishing-kits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingKitsIdRoute = PhishingKitsIdRouteImport.update({
  id: '/phishing-kits/$id',
  path: '/phishing-kits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerTemplatesRoute = ContentManagerTemplatesRouteImport.update({
  id: '/content-manager/templates',
  path: '/content-manager/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerSettingsRoute = ContentManagerSettingsRouteImport.update({
  id: '/content-manager/settings',
  path: '/content-manager/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerReportRoute = ContentManagerReportRouteImport.update({
  id: '/content-manager/report',
  path: '/content-manager/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerModulesRoute = ContentManagerModulesRouteImport.update({
  id: '/content-manager/modules',
  path: '/content-manager/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerHelpRoute = ContentManagerHelpRouteImport.update({
  id: '/content-manager/help',
  path: '/content-manager/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerCoursesRoute = ContentManagerCoursesRouteImport.update({
  id: '/content-manager/courses',
  path: '/content-manager/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerContentRoute = ContentManagerContentRouteImport.update({
  id: '/content-manager/content',
  path: '/content-manager/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsTimelineRoute = CampaignsTimelineRouteImport.update({
  id: '/campaigns/timeline',
  path: '/campaigns/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CampaignsIdIndexRoute = CampaignsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsIdRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const ContentManagerModulesNewRoute =
  ContentManagerModulesNewRouteImport.update({
    id: '/content-manager/modules_/new',
    path: '/content-manager/modules/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentManagerModulesModuleIdRoute =
  ContentManagerModulesModuleIdRouteImport.update({
    id: '/content-manager/modules_/$moduleId',
    path: '/content-manager/modules/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentManagerCoursesNewRoute =
  ContentManagerCoursesNewRouteImport.update({
    id: '/content-manager/courses_/new',
    path: '/content-manager/courses/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentManagerCoursesCourseIdRoute =
  ContentManagerCoursesCourseIdRouteImport.update({
    id: '/content-manager/courses_/$courseId',
    path: '/content-manager/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentManagerContentContentPieceIdRoute =
  ContentManagerContentContentPieceIdRouteImport.update({
    id: '/$contentPieceId',
    path: '/$contentPieceId',
    getParentRoute: () => ContentManagerContentRoute,
  } as any)
const CampaignsIdEditRoute = CampaignsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CampaignsIdRoute,
} as any)
const AdminTenantsNewTenantRoute = AdminTenantsNewTenantRouteImport.update({
  id: '/tenants/new-tenant',
  path: '/tenants/new-tenant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesCourseIdModulesModuleIdRoute =
  CoursesCourseIdModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const ContentManagerCoursesCourseIdEditRoute =
  ContentManagerCoursesCourseIdEditRouteImport.update({
    id: '/content-manager/courses_/$courseId_/edit',
    path: '/content-manager/courses/$courseId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance-org-manager': typeof ComplianceOrgManagerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/tenants-org-manager': typeof TenantsOrgManagerRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/timeline': typeof CampaignsTimelineRoute
  '/content-manager/content': typeof ContentManagerContentRouteWithChildren
  '/content-manager/courses': typeof ContentManagerCoursesRoute
  '/content-manager/help': typeof ContentManagerHelpRoute
  '/content-manager/modules': typeof ContentManagerModulesRoute
  '/content-manager/report': typeof ContentManagerReportRoute
  '/content-manager/settings': typeof ContentManagerSettingsRoute
  '/content-manager/templates': typeof ContentManagerTemplatesRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/phishing-kits/$id': typeof PhishingKitsIdRoute
  '/phishing-kits/new': typeof PhishingKitsNewRoute
  '/sending-profiles/$id': typeof SendingProfilesIdRoute
  '/sending-profiles/new': typeof SendingProfilesNewRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/new-tenant': typeof TenantsNewTenantRoute
  '/usergroups/$id': typeof UsergroupsIdRoute
  '/usergroups/new-group': typeof UsergroupsNewGroupRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/content-manager': typeof ContentManagerIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/phishing-kits': typeof PhishingKitsIndexRoute
  '/sending-profiles': typeof SendingProfilesIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/usergroups': typeof UsergroupsIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/new-tenant': typeof AdminTenantsNewTenantRoute
  '/campaigns/$id/edit': typeof CampaignsIdEditRoute
  '/content-manager/content/$contentPieceId': typeof ContentManagerContentContentPieceIdRoute
  '/content-manager/courses/$courseId': typeof ContentManagerCoursesCourseIdRoute
  '/content-manager/courses/new': typeof ContentManagerCoursesNewRoute
  '/content-manager/modules/$moduleId': typeof ContentManagerModulesModuleIdRoute
  '/content-manager/modules/new': typeof ContentManagerModulesNewRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/content-manager/courses/$courseId/edit': typeof ContentManagerCoursesCourseIdEditRoute
  '/courses/$courseId/modules/$moduleId': typeof CoursesCourseIdModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance-org-manager': typeof ComplianceOrgManagerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/tenants-org-manager': typeof TenantsOrgManagerRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/timeline': typeof CampaignsTimelineRoute
  '/content-manager/content': typeof ContentManagerContentRouteWithChildren
  '/content-manager/courses': typeof ContentManagerCoursesRoute
  '/content-manager/help': typeof ContentManagerHelpRoute
  '/content-manager/modules': typeof ContentManagerModulesRoute
  '/content-manager/report': typeof ContentManagerReportRoute
  '/content-manager/settings': typeof ContentManagerSettingsRoute
  '/content-manager/templates': typeof ContentManagerTemplatesRoute
  '/phishing-kits/$id': typeof PhishingKitsIdRoute
  '/phishing-kits/new': typeof PhishingKitsNewRoute
  '/sending-profiles/$id': typeof SendingProfilesIdRoute
  '/sending-profiles/new': typeof SendingProfilesNewRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/new-tenant': typeof TenantsNewTenantRoute
  '/usergroups/$id': typeof UsergroupsIdRoute
  '/usergroups/new-group': typeof UsergroupsNewGroupRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/content-manager': typeof ContentManagerIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/phishing-kits': typeof PhishingKitsIndexRoute
  '/sending-profiles': typeof SendingProfilesIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/usergroups': typeof UsergroupsIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/new-tenant': typeof AdminTenantsNewTenantRoute
  '/campaigns/$id/edit': typeof CampaignsIdEditRoute
  '/content-manager/content/$contentPieceId': typeof ContentManagerContentContentPieceIdRoute
  '/content-manager/courses/$courseId': typeof ContentManagerCoursesCourseIdRoute
  '/content-manager/courses/new': typeof ContentManagerCoursesNewRoute
  '/content-manager/modules/$moduleId': typeof ContentManagerModulesModuleIdRoute
  '/content-manager/modules/new': typeof ContentManagerModulesNewRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/campaigns/$id': typeof CampaignsIdIndexRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
  '/content-manager/courses/$courseId/edit': typeof ContentManagerCoursesCourseIdEditRoute
  '/courses/$courseId/modules/$moduleId': typeof CoursesCourseIdModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compliance-org-manager': typeof ComplianceOrgManagerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/templates': typeof TemplatesRoute
  '/tenants-org-manager': typeof TenantsOrgManagerRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/timeline': typeof CampaignsTimelineRoute
  '/content-manager/content': typeof ContentManagerContentRouteWithChildren
  '/content-manager/courses': typeof ContentManagerCoursesRoute
  '/content-manager/help': typeof ContentManagerHelpRoute
  '/content-manager/modules': typeof ContentManagerModulesRoute
  '/content-manager/report': typeof ContentManagerReportRoute
  '/content-manager/settings': typeof ContentManagerSettingsRoute
  '/content-manager/templates': typeof ContentManagerTemplatesRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/phishing-kits/$id': typeof PhishingKitsIdRoute
  '/phishing-kits/new': typeof PhishingKitsNewRoute
  '/sending-profiles/$id': typeof SendingProfilesIdRoute
  '/sending-profiles/new': typeof SendingProfilesNewRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/tenants/new-tenant': typeof TenantsNewTenantRoute
  '/usergroups/$id': typeof UsergroupsIdRoute
  '/usergroups/new-group': typeof UsergroupsNewGroupRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/content-manager/': typeof ContentManagerIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/phishing-kits/': typeof PhishingKitsIndexRoute
  '/sending-profiles/': typeof SendingProfilesIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/usergroups/': typeof UsergroupsIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/new-tenant': typeof AdminTenantsNewTenantRoute
  '/campaigns/$id/edit': typeof CampaignsIdEditRoute
  '/content-manager/content/$contentPieceId': typeof ContentManagerContentContentPieceIdRoute
  '/content-manager/courses_/$courseId': typeof ContentManagerCoursesCourseIdRoute
  '/content-manager/courses_/new': typeof ContentManagerCoursesNewRoute
  '/content-manager/modules_/$moduleId': typeof ContentManagerModulesModuleIdRoute
  '/content-manager/modules_/new': typeof ContentManagerModulesNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/campaigns/$id/': typeof CampaignsIdIndexRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
  '/content-manager/courses_/$courseId_/edit': typeof ContentManagerCoursesCourseIdEditRoute
  '/courses/$courseId/modules/$moduleId': typeof CoursesCourseIdModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compliance-org-manager'
    | '/dashboard'
    | '/help'
    | '/report'
    | '/settings'
    | '/statistics'
    | '/templates'
    | '/tenants-org-manager'
    | '/admin/help'
    | '/admin/logs'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/campaigns/timeline'
    | '/content-manager/content'
    | '/content-manager/courses'
    | '/content-manager/help'
    | '/content-manager/modules'
    | '/content-manager/report'
    | '/content-manager/settings'
    | '/content-manager/templates'
    | '/courses/$courseId'
    | '/phishing-kits/$id'
    | '/phishing-kits/new'
    | '/sending-profiles/$id'
    | '/sending-profiles/new'
    | '/tenants/$id'
    | '/tenants/new-tenant'
    | '/usergroups/$id'
    | '/usergroups/new-group'
    | '/admin/'
    | '/campaigns'
    | '/content-manager'
    | '/courses'
    | '/phishing-kits'
    | '/sending-profiles'
    | '/tenants'
    | '/usergroups'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/new-tenant'
    | '/campaigns/$id/edit'
    | '/content-manager/content/$contentPieceId'
    | '/content-manager/courses/$courseId'
    | '/content-manager/courses/new'
    | '/content-manager/modules/$moduleId'
    | '/content-manager/modules/new'
    | '/admin/tenants'
    | '/courses/$courseId/'
    | '/content-manager/courses/$courseId/edit'
    | '/courses/$courseId/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance-org-manager'
    | '/dashboard'
    | '/help'
    | '/report'
    | '/settings'
    | '/statistics'
    | '/templates'
    | '/tenants-org-manager'
    | '/admin/help'
    | '/admin/logs'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/campaigns/new'
    | '/campaigns/timeline'
    | '/content-manager/content'
    | '/content-manager/courses'
    | '/content-manager/help'
    | '/content-manager/modules'
    | '/content-manager/report'
    | '/content-manager/settings'
    | '/content-manager/templates'
    | '/phishing-kits/$id'
    | '/phishing-kits/new'
    | '/sending-profiles/$id'
    | '/sending-profiles/new'
    | '/tenants/$id'
    | '/tenants/new-tenant'
    | '/usergroups/$id'
    | '/usergroups/new-group'
    | '/admin'
    | '/campaigns'
    | '/content-manager'
    | '/courses'
    | '/phishing-kits'
    | '/sending-profiles'
    | '/tenants'
    | '/usergroups'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/new-tenant'
    | '/campaigns/$id/edit'
    | '/content-manager/content/$contentPieceId'
    | '/content-manager/courses/$courseId'
    | '/content-manager/courses/new'
    | '/content-manager/modules/$moduleId'
    | '/content-manager/modules/new'
    | '/admin/tenants'
    | '/campaigns/$id'
    | '/courses/$courseId'
    | '/content-manager/courses/$courseId/edit'
    | '/courses/$courseId/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compliance-org-manager'
    | '/dashboard'
    | '/help'
    | '/report'
    | '/settings'
    | '/statistics'
    | '/templates'
    | '/tenants-org-manager'
    | '/admin/help'
    | '/admin/logs'
    | '/admin/report'
    | '/admin/settings'
    | '/admin/users'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/campaigns/timeline'
    | '/content-manager/content'
    | '/content-manager/courses'
    | '/content-manager/help'
    | '/content-manager/modules'
    | '/content-manager/report'
    | '/content-manager/settings'
    | '/content-manager/templates'
    | '/courses/$courseId'
    | '/phishing-kits/$id'
    | '/phishing-kits/new'
    | '/sending-profiles/$id'
    | '/sending-profiles/new'
    | '/tenants/$id'
    | '/tenants/new-tenant'
    | '/usergroups/$id'
    | '/usergroups/new-group'
    | '/admin/'
    | '/campaigns/'
    | '/content-manager/'
    | '/courses/'
    | '/phishing-kits/'
    | '/sending-profiles/'
    | '/tenants/'
    | '/usergroups/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/new-tenant'
    | '/campaigns/$id/edit'
    | '/content-manager/content/$contentPieceId'
    | '/content-manager/courses_/$courseId'
    | '/content-manager/courses_/new'
    | '/content-manager/modules_/$moduleId'
    | '/content-manager/modules_/new'
    | '/admin/tenants/'
    | '/campaigns/$id/'
    | '/courses/$courseId/'
    | '/content-manager/courses_/$courseId_/edit'
    | '/courses/$courseId/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComplianceOrgManagerRoute: typeof ComplianceOrgManagerRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  TemplatesRoute: typeof TemplatesRoute
  TenantsOrgManagerRoute: typeof TenantsOrgManagerRoute
  CampaignsIdRoute: typeof CampaignsIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsTimelineRoute: typeof CampaignsTimelineRoute
  ContentManagerContentRoute: typeof ContentManagerContentRouteWithChildren
  ContentManagerCoursesRoute: typeof ContentManagerCoursesRoute
  ContentManagerHelpRoute: typeof ContentManagerHelpRoute
  ContentManagerModulesRoute: typeof ContentManagerModulesRoute
  ContentManagerReportRoute: typeof ContentManagerReportRoute
  ContentManagerSettingsRoute: typeof ContentManagerSettingsRoute
  ContentManagerTemplatesRoute: typeof ContentManagerTemplatesRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  PhishingKitsIdRoute: typeof PhishingKitsIdRoute
  PhishingKitsNewRoute: typeof PhishingKitsNewRoute
  SendingProfilesIdRoute: typeof SendingProfilesIdRoute
  SendingProfilesNewRoute: typeof SendingProfilesNewRoute
  TenantsIdRoute: typeof TenantsIdRoute
  TenantsNewTenantRoute: typeof TenantsNewTenantRoute
  UsergroupsIdRoute: typeof UsergroupsIdRoute
  UsergroupsNewGroupRoute: typeof UsergroupsNewGroupRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ContentManagerIndexRoute: typeof ContentManagerIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PhishingKitsIndexRoute: typeof PhishingKitsIndexRoute
  SendingProfilesIndexRoute: typeof SendingProfilesIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UsergroupsIndexRoute: typeof UsergroupsIndexRoute
  ContentManagerCoursesCourseIdRoute: typeof ContentManagerCoursesCourseIdRoute
  ContentManagerCoursesNewRoute: typeof ContentManagerCoursesNewRoute
  ContentManagerModulesModuleIdRoute: typeof ContentManagerModulesModuleIdRoute
  ContentManagerModulesNewRoute: typeof ContentManagerModulesNewRoute
  ContentManagerCoursesCourseIdEditRoute: typeof ContentManagerCoursesCourseIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants-org-manager': {
      id: '/tenants-org-manager'
      path: '/tenants-org-manager'
      fullPath: '/tenants-org-manager'
      preLoaderRoute: typeof TenantsOrgManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-org-manager': {
      id: '/compliance-org-manager'
      path: '/compliance-org-manager'
      fullPath: '/compliance-org-manager'
      preLoaderRoute: typeof ComplianceOrgManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usergroups/': {
      id: '/usergroups/'
      path: '/usergroups'
      fullPath: '/usergroups'
      preLoaderRoute: typeof UsergroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sending-profiles/': {
      id: '/sending-profiles/'
      path: '/sending-profiles'
      fullPath: '/sending-profiles'
      preLoaderRoute: typeof SendingProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing-kits/': {
      id: '/phishing-kits/'
      path: '/phishing-kits'
      fullPath: '/phishing-kits'
      preLoaderRoute: typeof PhishingKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/': {
      id: '/content-manager/'
      path: '/content-manager'
      fullPath: '/content-manager'
      preLoaderRoute: typeof ContentManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/usergroups/new-group': {
      id: '/usergroups/new-group'
      path: '/usergroups/new-group'
      fullPath: '/usergroups/new-group'
      preLoaderRoute: typeof UsergroupsNewGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usergroups/$id': {
      id: '/usergroups/$id'
      path: '/usergroups/$id'
      fullPath: '/usergroups/$id'
      preLoaderRoute: typeof UsergroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new-tenant': {
      id: '/tenants/new-tenant'
      path: '/tenants/new-tenant'
      fullPath: '/tenants/new-tenant'
      preLoaderRoute: typeof TenantsNewTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sending-profiles/new': {
      id: '/sending-profiles/new'
      path: '/sending-profiles/new'
      fullPath: '/sending-profiles/new'
      preLoaderRoute: typeof SendingProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sending-profiles/$id': {
      id: '/sending-profiles/$id'
      path: '/sending-profiles/$id'
      fullPath: '/sending-profiles/$id'
      preLoaderRoute: typeof SendingProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing-kits/new': {
      id: '/phishing-kits/new'
      path: '/phishing-kits/new'
      fullPath: '/phishing-kits/new'
      preLoaderRoute: typeof PhishingKitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing-kits/$id': {
      id: '/phishing-kits/$id'
      path: '/phishing-kits/$id'
      fullPath: '/phishing-kits/$id'
      preLoaderRoute: typeof PhishingKitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/templates': {
      id: '/content-manager/templates'
      path: '/content-manager/templates'
      fullPath: '/content-manager/templates'
      preLoaderRoute: typeof ContentManagerTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/settings': {
      id: '/content-manager/settings'
      path: '/content-manager/settings'
      fullPath: '/content-manager/settings'
      preLoaderRoute: typeof ContentManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/report': {
      id: '/content-manager/report'
      path: '/content-manager/report'
      fullPath: '/content-manager/report'
      preLoaderRoute: typeof ContentManagerReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/modules': {
      id: '/content-manager/modules'
      path: '/content-manager/modules'
      fullPath: '/content-manager/modules'
      preLoaderRoute: typeof ContentManagerModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/help': {
      id: '/content-manager/help'
      path: '/content-manager/help'
      fullPath: '/content-manager/help'
      preLoaderRoute: typeof ContentManagerHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/courses': {
      id: '/content-manager/courses'
      path: '/content-manager/courses'
      fullPath: '/content-manager/courses'
      preLoaderRoute: typeof ContentManagerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/content': {
      id: '/content-manager/content'
      path: '/content-manager/content'
      fullPath: '/content-manager/content'
      preLoaderRoute: typeof ContentManagerContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/timeline': {
      id: '/campaigns/timeline'
      path: '/campaigns/timeline'
      fullPath: '/campaigns/timeline'
      preLoaderRoute: typeof CampaignsTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/campaigns/$id/': {
      id: '/campaigns/$id/'
      path: '/'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof CampaignsIdIndexRouteImport
      parentRoute: typeof CampaignsIdRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/content-manager/modules_/new': {
      id: '/content-manager/modules_/new'
      path: '/content-manager/modules/new'
      fullPath: '/content-manager/modules/new'
      preLoaderRoute: typeof ContentManagerModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/modules_/$moduleId': {
      id: '/content-manager/modules_/$moduleId'
      path: '/content-manager/modules/$moduleId'
      fullPath: '/content-manager/modules/$moduleId'
      preLoaderRoute: typeof ContentManagerModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/courses_/new': {
      id: '/content-manager/courses_/new'
      path: '/content-manager/courses/new'
      fullPath: '/content-manager/courses/new'
      preLoaderRoute: typeof ContentManagerCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/courses_/$courseId': {
      id: '/content-manager/courses_/$courseId'
      path: '/content-manager/courses/$courseId'
      fullPath: '/content-manager/courses/$courseId'
      preLoaderRoute: typeof ContentManagerCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/content/$contentPieceId': {
      id: '/content-manager/content/$contentPieceId'
      path: '/$contentPieceId'
      fullPath: '/content-manager/content/$contentPieceId'
      preLoaderRoute: typeof ContentManagerContentContentPieceIdRouteImport
      parentRoute: typeof ContentManagerContentRoute
    }
    '/campaigns/$id/edit': {
      id: '/campaigns/$id/edit'
      path: '/edit'
      fullPath: '/campaigns/$id/edit'
      preLoaderRoute: typeof CampaignsIdEditRouteImport
      parentRoute: typeof CampaignsIdRoute
    }
    '/admin/tenants/new-tenant': {
      id: '/admin/tenants/new-tenant'
      path: '/tenants/new-tenant'
      fullPath: '/admin/tenants/new-tenant'
      preLoaderRoute: typeof AdminTenantsNewTenantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$courseId/modules/$moduleId': {
      id: '/courses/$courseId/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/courses/$courseId/modules/$moduleId'
      preLoaderRoute: typeof CoursesCourseIdModulesModuleIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/content-manager/courses_/$courseId_/edit': {
      id: '/content-manager/courses_/$courseId_/edit'
      path: '/content-manager/courses/$courseId/edit'
      fullPath: '/content-manager/courses/$courseId/edit'
      preLoaderRoute: typeof ContentManagerCoursesCourseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminHelpRoute: typeof AdminHelpRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminReportRoute: typeof AdminReportRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
  AdminTenantsNewTenantRoute: typeof AdminTenantsNewTenantRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHelpRoute: AdminHelpRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminReportRoute: AdminReportRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
  AdminTenantsNewTenantRoute: AdminTenantsNewTenantRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CampaignsIdRouteChildren {
  CampaignsIdEditRoute: typeof CampaignsIdEditRoute
  CampaignsIdIndexRoute: typeof CampaignsIdIndexRoute
}

const CampaignsIdRouteChildren: CampaignsIdRouteChildren = {
  CampaignsIdEditRoute: CampaignsIdEditRoute,
  CampaignsIdIndexRoute: CampaignsIdIndexRoute,
}

const CampaignsIdRouteWithChildren = CampaignsIdRoute._addFileChildren(
  CampaignsIdRouteChildren,
)

interface ContentManagerContentRouteChildren {
  ContentManagerContentContentPieceIdRoute: typeof ContentManagerContentContentPieceIdRoute
}

const ContentManagerContentRouteChildren: ContentManagerContentRouteChildren = {
  ContentManagerContentContentPieceIdRoute:
    ContentManagerContentContentPieceIdRoute,
}

const ContentManagerContentRouteWithChildren =
  ContentManagerContentRoute._addFileChildren(
    ContentManagerContentRouteChildren,
  )

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
  CoursesCourseIdModulesModuleIdRoute: typeof CoursesCourseIdModulesModuleIdRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
  CoursesCourseIdModulesModuleIdRoute: CoursesCourseIdModulesModuleIdRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ComplianceOrgManagerRoute: ComplianceOrgManagerRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  TemplatesRoute: TemplatesRoute,
  TenantsOrgManagerRoute: TenantsOrgManagerRoute,
  CampaignsIdRoute: CampaignsIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsTimelineRoute: CampaignsTimelineRoute,
  ContentManagerContentRoute: ContentManagerContentRouteWithChildren,
  ContentManagerCoursesRoute: ContentManagerCoursesRoute,
  ContentManagerHelpRoute: ContentManagerHelpRoute,
  ContentManagerModulesRoute: ContentManagerModulesRoute,
  ContentManagerReportRoute: ContentManagerReportRoute,
  ContentManagerSettingsRoute: ContentManagerSettingsRoute,
  ContentManagerTemplatesRoute: ContentManagerTemplatesRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  PhishingKitsIdRoute: PhishingKitsIdRoute,
  PhishingKitsNewRoute: PhishingKitsNewRoute,
  SendingProfilesIdRoute: SendingProfilesIdRoute,
  SendingProfilesNewRoute: SendingProfilesNewRoute,
  TenantsIdRoute: TenantsIdRoute,
  TenantsNewTenantRoute: TenantsNewTenantRoute,
  UsergroupsIdRoute: UsergroupsIdRoute,
  UsergroupsNewGroupRoute: UsergroupsNewGroupRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ContentManagerIndexRoute: ContentManagerIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PhishingKitsIndexRoute: PhishingKitsIndexRoute,
  SendingProfilesIndexRoute: SendingProfilesIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsergroupsIndexRoute: UsergroupsIndexRoute,
  ContentManagerCoursesCourseIdRoute: ContentManagerCoursesCourseIdRoute,
  ContentManagerCoursesNewRoute: ContentManagerCoursesNewRoute,
  ContentManagerModulesModuleIdRoute: ContentManagerModulesModuleIdRoute,
  ContentManagerModulesNewRoute: ContentManagerModulesNewRoute,
  ContentManagerCoursesCourseIdEditRoute:
    ContentManagerCoursesCourseIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
