sonar.projectKey=PEI-SecureLearning_api
sonar.organization=pei-securelearning
sonar.projectName=SecureLearning API

sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8

# Python coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=src/models/**,src/core/**,src/main.py

# Exclude generated / non-source
sonar.exclusions=**/__pycache__/**,**/*.pyc,api.egg-info/**
