name: "Build Release Images"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hotfix/**

jobs:
  api:
    uses: ./.github/workflows/ci-api.yml
    with:
      environment: production
      image_tag: latest
      include_sha_tag: true
      push_image: true
    secrets: inherit

  web:
    uses: ./.github/workflows/ci-web.yml
    with:
      environment: production
      image_tag: latest
      include_sha_tag: true
      push_image: true
    secrets: inherit

  smtp:
    uses: ./.github/workflows/ci-smtp.yml
    with:
      environment: production
      image_tag: latest
      include_sha_tag: true
      push_image: true
    secrets: inherit
