sonar.projectKey=PEI-SecureLearning_web
sonar.organization=pei-securelearning
sonar.projectName=SecureLearning Web

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Exclude generated / non-source
sonar.exclusions=**/node_modules/**,dist/**,routeTree.gen.ts
